management/editor/editor.go, system/admin/handlers.go, system/admin/server.go, system/admin/static/dashboard/css/admin.css, system/db/content.go
Added the ability to delete posts or other types using the standard editor only on pages at /admin/edit
=> [fundamental-feature] Delete Content

README.md, cmd/ponzu/options.go
**Note:** if you intend to work on your own fork and contribute from it, you will
need to also pass `--fork=path/to/your/fork` (using OS-standard filepath structure),
where `path/to/your/fork` _must_ be within `$GOPATH/src`, and you are working from a branch
called `ponxu-dev`.
=> [contrib] Adding details about contributing and using the ponzu cli

cmd/ponzu/main.go, system/admin/admin.go, system/admin/handlers.go, system/admin/server.go, system/admin/static/dashboard/css/admin.css, system/admin/user/auth.go, system/db/content.go, system/db/user.go, system/tls/enable.go
This PR adds the ability for an admin to change its account email/password, and add/remove other admin users.
Still working on the best way to handle password recovery.. since I am not sure how reliable postfix/sendmail installations are on various Linux servers, it is hard to build a consistent experience around host-based emailing. Also, as I would like this to be cross platform, especially to support Windows, a solution that covers all OS would be ideal. Unfortunately, this might mean using a less secure recovery pattern like "Secret Question" or similar.
=> [core] User management

LICENSE, cmd/ponzu/LICENSE
All code authored by Ponzu contributors shall be under the BSD-3 license.
```
Copyright (c) 2016 Boss Sauce Creative, LLC. All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:
* Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.
* Neither the name of Boss Sauce Creative, Ponzu, nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior …
```
=> [core] adding BSD licesne

cmd/ponzu/main.go
In addition to adding much-needed documentation in the usage for our CLI, a better help feature was added so users can selectively show usage on a per-command basis. For example:
```
$ ponzu help generate
generate, gen, g <type (,...fields)>:
Generate a content type file with boilerplate code to implement
the editor.Editable interface. Must be given one (1) parameter of
the name of the type for the new content. The fields following a 
type determine the field names and types of the content struct to 
be generated. These must be in the following format:
fieldName:"T"
Example:
$ ponzu gen review title:"string" body:"string" rating:"int" tags:"[]string"
The command above will generate a file 'content/review.go' with boilerplate
methods, as well as struct definition, and cooresponding field …
```
=> [tooling] Better usage and help via CLI

cmd/ponzu/main.go, management/editor/editor.go, management/manager/manager.go, system/admin/admin.go
thanks, @crackcomm - especially like this:
https://github.com/ponzu-cms/ponzu/pull/35/files#diff-efaf441b35a404da9da27172a87b1dceR96
"naked" return there makes a lot of sense.
=> [core] code clean-up

system/admin/handlers.go, system/api/external.go, system/db/config.go
=> [core] Consistent order of saved repeater items

system/api/external.go
This PR fixes a godoc link for externalable API.
=> fixes #56 godoc link

README.md, cmd/ponzu/usage.go, deployment/README.md
s/cooresponding/corresponding/
=> Another typo fix in readme

cmd/ponzu/main.go, cmd/ponzu/options.go, cmd/ponzu/paths.go
Big thank you to @Sirikon for the PR adding windows support!
=> [core] Windows build & run support

examples/updateable/content/song.go
Logging id rather than title in AfterAcceptUpdate, moved BeforeAcceptUpdate for clarity.
=> logging id rather than title in AfterAcceptUpdate

system/db/content.go
Fix for #76 
TODO: consider adding a configuration field for `waitDuration` value.
=> [core] add throttling to db content sorting call

system/api/search.go, system/db/content.go, system/db/init.go, system/item/item.go, system/search/search.go
Give search its own package separate from the `system/db` package
=> [core] moving search into own package and renaming funcs throughout

system/db/content.go
Resolves issue with only the latest repo being shown on batch update until clicking within the editor to trigger SortContent again.
=> improved throttle to ensure content is sorted

management/editor/repeaters.go
big thanks to @kkeuning who first identified this issue and pushed a nifty fix!
=> [core] update with better sort throttling 

cmd/ponzu/main.go, system/db/init.go
=> Revert "Fix for search not working when addons are enabled"

cmd/ponzu/main.go, system/db/init.go
@nilslice I resubmitted #157 regarding issue #153
=> delayed indexer init (fix for search not working when addons are enabled)

cmd/ponzu/main.go, system/db/init.go
big thanks to @guycalledseven for finding and fixing this bug!
=> [core] defer search indexing until addons/item types are registered

system/admin/handlers.go, system/admin/upload/backup.go, system/backup/archive.go, system/search/backup.go
=> Add backup routine to search

system/admin/handlers.go, system/backup/archive.go, system/search/backup.go
Huge thanks to @tom-f for this contribution! This should be a good start to enable more contributors and addon developers to eventually leverage an interface and registry to provide simple backup procedure for future features and the data they use/create.
=> [core] Add search index backup routine

.gitignore
fix for #185, thank you @shusson!
=> [repo] localize all ignore paths to top level

README.md, docs/src/CLI/General-Usage.md
=> docs and readme updated to remove an excessive struct field (#106)

cmd/ponzu/vendor/golang.org/x/crypto/autocert/autocert.go, cmd/ponzu/vendor/golang.org/x/crypto/autocert/autocert_test.go, cmd/ponzu/vendor/golang.org/x/crypto/autocert/cache.go, cmd/ponzu/vendor/golang.org/x/crypto/autocert/cache_test.go, cmd/ponzu/vendor/golang.org/x/crypto/autocert/example_test.go, cmd/ponzu/vendor/golang.org/x/crypto/autocert/listener.go, cmd/ponzu/vendor/golang.org/x/crypto/autocert/renewal.go, cmd/ponzu/vendor/golang.org/x/crypto/autocert/renewal_test.go, system/tls/enable.go
upgrade to latest `acme/autocert` pkg, and implement handler for "http-01" challenge
=> Update to meet Let's Encrypt challenge requirment

cmd/ponzu/new.go
Spent some time looking through your project – good job man! 
Will try to find some time to dig more into the code when I have the chance 👍
=> Fix typo in 'new' help-text`

cmd/ponzu/new.go
=> Fix typo in 'new' help-text` (#227)

cmd/ponzu/add.go
=> expanded help to mention need to import addon

cmd/ponzu/usage.go
Sorry for all the pull messages. First time doing multiple PRs. This one is good.
Closes #206.
=> Override Cobra's 'help' command to remove duplicate.

system/item/item.go
Tested, regex replace still works on file uploads as intended.
=> Compile regex once instead of each time function is called.

README.md
https://en.wikipedia.org/wiki/Illustration
=> Typo illustration

system/admin/upload/backup.go, system/backup/archive.go, system/search/backup.go
See #289. Thank you, @vkuznecovas!
=> backup: follow symlinks when archiving
