ponzu-cms/ponzu

- cmd/ponzu/main.go
- content/item.go
- management/editor/editor.go
- management/editor/elements.go
- management/manager/manager.go
- system/admin/handlers.go
- system/admin/static/common/js/util.js
- system/admin/upload.go
- system/api/handlers.go
Added the necessary changes across the codebase to support more rich time recording, which will also help add sorting later on. 
```go
type Item struct {
ID        int    `json:"id"`
Slug      string `json:"slug"`
Timestamp int64  `json:"timestamp"`
Updated   int64  `json:"updated"`
}
```
Also, added a useful Timestamp function to use as an editor input element. Note for future additional input elements how the data field is set based on the return reflect value from `valueFromStructField()`: 
```go
func Timestamp(fieldName string, p interface{}, attrs map[string]string) []byte {
var data string
val := valueFromStructField(fieldName, p)
if val.Int() == 0 {
data = ""
} else {
data = fmt.Sprintf("%d", val.Int())
}
e := &element{
TagName: "input",
Attrs:   attrs,
Name: …
```
> [core] move content.Item to unix-y Timestamp and Updated fields

- content/item.go
- management/editor/editor.go
- management/editor/elements.go
- management/manager/manager.go
- system/admin/config/config.go
- system/admin/handlers.go
- system/admin/static/dashboard/css/admin.css
- system/admin/static/editor/js/materialNote.js
- system/db/content.go
- system/db/init.go
This PR adds a few things: 
1. Content type posts sortable by time (via the `editor.Sortable` interface) 
2. Implementation of sorting inside Admin 
3. Quick delete of post from post list and search results
Since sorting can take some time when db size is large, it is _almost_ always done in its own goroutine, with the exception of the admin delete handler. Additionally, to avoid re-sorting content posts per API query, we keep a sorted bucket of posts in the db to be quickly retrieved. This sorted bucket is re-created each time new content is added, edited, or deleted.
With regards to the `Sortable` interface, there is some overlap with the `Editable` interface. In at least one occasion, I do a type assertion in the same function from a content type to `Editable` then again later from a …
> [fundamental feature] Content type posts are sorted by time and cached in Admin, API coming soon.

- cmd/ponzu/main.go
- cmd/ponzu/vendor/golang.org/x/crypto/autocert/autocert.go
- cmd/ponzu/vendor/golang.org/x/crypto/autocert/autocert_test.go
- cmd/ponzu/vendor/golang.org/x/crypto/autocert/cache.go
- cmd/ponzu/vendor/golang.org/x/crypto/autocert/cache_test.go
- cmd/ponzu/vendor/golang.org/x/crypto/autocert/renewal.go
- cmd/ponzu/vendor/golang.org/x/crypto/autocert/renewal_test.go
- cmd/ponzu/vendor/golang.org/x/net/context/context.go
- cmd/ponzu/vendor/golang.org/x/net/context/context_test.go
- cmd/ponzu/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go
- cmd/ponzu/vendor/golang.org/x/net/context/ctxhttp/ctxhttp_17_test.go
- cmd/ponzu/vendor/golang.org/x/net/context/ctxhttp/ctxhttp_pre17.go
- cmd/ponzu/vendor/golang.org/x/net/context/ctxhttp/ctxhttp_pre17_test.go
- cmd/ponzu/vendor/golang.org/x/net/context/ctxhttp/ctxhttp_test.go
- cmd/ponzu/vendor/golang.org/x/net/context/go17.go
- cmd/ponzu/vendor/golang.org/x/net/context/pre_go17.go
- cmd/ponzu/vendor/golang.org/x/net/context/withtimeout_test.go
- system/admin/config/config.go
- system/admin/handlers.go
- system/tls/enable.go
- system/tls/init.go
Thanks to the incredible work done by [Let's Encrypt](https://letsencrypt.org) and the Go contributors who wrote the golang.org/x/crypto/acme/autocert package, TLS support is live in Ponzu, behind the `--https` flag (which used to be referenced as --tls, changed for code organization/naming reasons)
Automatic, free TLS is great for a number of reasons, including: 
1. Encryption - respect the privacy of users and make the Internet a little safer
2. HTTP/2 - Go 1.6 [added http2 support](https://golang.org/doc/go1.6#http2) and this makes it that much easier to leverage the powerful new protocol
3. Simplicity - no need to manage SSL certificates, generating keys, or upgrading/renewing 
**Notes about Let's Encrypt configuration:**
- Certs will auto-renew within 30 days of expiration
- If …
> [core] Adding support for automatic TLS / SSL via Let's Encrypt

- system/api/handlers.go
Now enabling API consumers to sort and limit the system responses based on query string params: 
`/api/posts?type=Post&count=20&order=desc&offset=1`
(more info in bosssauce/ponzu#3) 
This will eventually also be added to the Admin interface to implement pagination.
> [fundamental-feature] Sort, count, offset (pagination) in API responses

- cmd/ponzu/options.go
- content/post.go
- management/editor/elements.go
- system/admin/static/dashboard/css/admin.css
This allows CMS users to arbitrarily add 'tags' to their content, given the field name provided. 
```go
editor.Field{
View: editor.Tags("Category", p, map[string]string{
"label": "Post Categories",
}),
},
```
> [core] Adding input func for Tags

- cmd/ponzu/main.go
- cmd/ponzu/options.go
- content/post.go
- management/editor/editor.go
- system/admin/admin.go
- system/admin/handlers.go
- system/admin/server.go
- system/admin/static/common/js/util.js
- system/admin/static/dashboard/css/admin.css
- system/admin/upload.go
- system/admin/upload/upload.go
- system/api/analytics/analytics.go
- system/api/analytics/init.go
- system/api/external.go
- system/api/handlers.go
- system/db/content.go
- system/db/init.go
I'm excited about this feature, having built numerous apps to handle user-submitted content which would then be re-displayed publicly. This PR is mostly about the two new interfaces and their use for externally submitted content, and the admin's ability to merge that content into the internal feed.
```go
// Externalable accepts or rejects external POST requests to endpoints such as:
// /external/posts?type=Review
type Externalable interface {
// Accepts determines whether a type will allow external submissions
Accepts() bool
}
```
```go
// Mergeable allows external post content to be approved and published through
// the public-facing API
type Mergeable interface {
// Approve copies an external post to the internal collection and triggers
// a re-sort of its content type posts
Approve(req …
```
> [core] Enable content to be submitted from external clients

- management/editor/editor.go
- system/admin/handlers.go
- system/admin/upload/upload.go
- system/api/analytics/batch.go
- system/api/analytics/init.go
- system/api/handlers.go
- system/api/server.go
- system/db/content.go
Adding a Query func to the db package that only retrieves data based on the passed options, instead of pulling everything out of a certain namespace and cutting it up as needed.. 
```go
// Query retrieves a set of content from the db based on options
func Query(namespace string, opts QueryOptions) [][]byte {
var posts [][]byte
store.View(func(tx *bolt.Tx) error {
b := tx.Bucket([]byte(namespace))
if b == nil {
return nil
}
c := b.Cursor()
n := b.Stats().KeyN
var start, end int
switch opts.Count {
case -1:
start = 0
end = n
default:
start = opts.Count * opts.Offset
end = start + opts.Count
}
// bounds check on posts given the start & end count
if start > n {
start = n - opts.Count
}
if end > n {
end = n
}
i := 0   // count of num posts added
cur := 0 // count of num cursor moves
switch …
```
> [core] More efficient DB queries

- system/admin/handlers.go
Will need to do a more thorough scan of all type assertions to log this message out to the programmer/user so they know an action couldn't be completed due to implementation failure of necessary interface(s).
> [core] better error logging for interface type assertions

- cmd/ponzu/contentType.tmpl
- cmd/ponzu/vendor/github.com/nilslice/email/README.md
- cmd/ponzu/vendor/github.com/nilslice/email/email.go
- content/item.go
- content/types.go
- management/editor/editor.go
- management/editor/elements.go
- management/manager/process.go
- system/admin/admin.go
- system/admin/config/config.go
- system/admin/handlers.go
- system/admin/server.go
- system/api/analytics/init.go
- system/api/external.go
- system/api/handlers.go
- system/api/server.go
- system/db/config.go
- system/db/content.go
- system/db/init.go
- system/db/user.go
- system/tls/enable.go
This PR addresses the need for admins to recover their accounts by verifying their email address in the event that they lost or forgot their account password. Upon account recovery request, Ponzu sends an email to the account on record with a unique and immediately generated key, which is used to verify their ownership of the account. 
This uses github.com/nilslice/email SMTP client to send emails. Beware of IP blacklisting -- try not to execute this feature on a residential IP address as it is likely already blacklisted and will fail. 
Also, pagination is now live in the admin UI for all content, public & pending alike.
> [core] Added account recovery process and content pagination in admin UI

- system/api/analytics/init.go
Rather than recalculating metrics for days prior to today (where data should never change) we now store these in a `__metrics` bucket. This reduces CPU on higher load systems. Though, there is still fairly high CPU usage at extremes. If there is interest or need, we can further optimize this or offer a way to toggle analytics completely.
> [core] API request metrics are now stored per day

- content/item.go
- management/manager/manager.go
- system/admin/handlers.go
- system/api/handlers.go
- system/db/content.go
- system/db/init.go
There is a high likelihood of users wanting to set slugs as the top-level URL structure for their public content routing. So rather than making a client-side map of content slugs to type & id to issue an API call, this PR allows the API call to be made with just a slug as a parameter.
Example:
<pre>GET    /api/content&slug=some-assigned-slug-value</pre>
*(other params are ignored)*
> [core] Add a index for content slugs allowing quicker lookup via slug

- README.md
- management/editor/elements.go
- management/editor/repeaters.go
- management/manager/manager.go
- system/admin/handlers.go
- system/admin/static/dashboard/css/admin.css
- system/api/external.go
- system/db/config.go
This PR introduces a new form editor input feature, "Repeaters". From time to time, it's not uncommon that a CMS user wants to add an arbitrary number of inputs for any single field. For example, a music playlist: each playlist has a name, and some varying number of songs associated. With Ponzu's new Repeaters, you can opt to make a Form editor which allows the user to add or remove any number of inputs within a field. 
For any type, such as:
```go
type Playlist struct {
Songs []string `json:"songs"`
}
```
a corresponding MarshalEditor method would look like (take note of the InputRepeater):
```go
func (p *Playlist) MarshalEditor() ([]byte, error) {
view, err := editor.Form(p,
editor.Field{
View: editor.InputRepeater("Songs", p, map[string]string{
"label":       "Songs",
"type": …
```
> [core] Repeatable form input elements

- cmd/ponzu/main.go
- cmd/ponzu/options.go
- cmd/ponzu/usage.go
- cmd/ponzu/vendor/golang.org/x/net/context/context_test.go
- management/editor/dom.go
- management/editor/editor.go
- management/editor/elements.go
- management/editor/repeaters.go
- system/api/handlers.go
- system/db/config.go
- system/tls/devcerts.go
- system/tls/enable.go
- system/tls/enabledev.go
This PR adds the ability to pass a special `--gocmd` flag to specify a version of the Go tool to use. This is useful when working with different go versions, like at the time of this writing `go1.8beta2` being tested.
Additionally, in order to test HTTP/2 locally, passing the `--devhttps`  flag will auto-generate self-signed SSL certificates and start a TLS server utilizing the generated certs.
> [tooling] Add Go command flag, auto-generate self-signed SSL for development

- README.md
- cmd/ponzu/main.go
- cmd/ponzu/usage.go
- system/addon/api.go
- system/admin/config/config.go
- system/admin/handlers.go
- system/admin/server.go
- system/admin/upload/upload.go
- system/api/external.go
- system/api/handlers.go
- system/api/server.go
- system/db/addon.go
- system/db/cache.go
- system/db/config.go
- system/db/content.go
- system/db/init.go
- system/db/user.go
- system/tls/devcerts.go
- system/tls/enable.go
This PR enables admins to disable/enable CORS and GZIP from within the admin CMS configuration page. Both are enabled by default.
Note: currently, the GZIP implementation is 100% on the fly, for every qualifying API endpoint request. This could add significant CPU usage, but dramatically decreases bandwidth. Will be considering other better implementations, but for now YMMV.
Possible optimizations:
- pooling gzip Writers vs. creating a new one for each response
- caching gzipped responses (in memory? on disk?) 
- enforcing size threshold (only gzip content larger than N bytes)
> [core] Adding toggle for CORS, GZIP in admin/cms configuration

- cmd/ponzu/main.go
- management/editor/editor.go
- management/manager/manager.go
- system/admin/admin.go
I did it during reading the code.
> Just a little cleaner code

- system/admin/config/config.go
- system/admin/handlers.go
- system/admin/server.go
- system/admin/upload/backup.go
- system/api/analytics/backup.go
- system/api/analytics/init.go
- system/auth.go
- system/db/backup.go
This PR provides a simple HTTP interface to create and download backups of your Ponzu databases and `uploads` directory. 
`/admin/backup?source={uploads,analytics,system}`
The endpoint requires Basic Auth, and the username and password must be provided by an admin in the Configuration section of the CMS. If there are no username or password credentials stored, the endpoint will return a 403 Forbidden. If the credentials provided are incorrect, a 401 Unauthorized is returned. 
The idea is that you will establish backup routines on a machine that could simply execute:
```bash
curl "https://user:pass@hostname?source=uploads" > uploads.bak.tar.gz
curl "https://user:pass@hostname?source=system" > system.db.bak
curl "https://user:pass@hostname?source=analytics" > analytics.db.bak
```
Uploads …
> [core] System backups (uploads, system.db, analytics.db)

- system/api/handlers.go
Fix for #43 
`gzipResponseWriter` needed to implement `http.Pusher` and additionally set the `Accept-Encoding` header on the `http.PushOptions` struct argument.
Also removed `defer` from the call to `push` in handlers, since its likely that `Pushable` references are dependencies of their parent content.
> [core] implement http.Pusher on our composite gzip/response writer 

- README.md
- cmd/ponzu/usage.go
- deployment/README.md
- system/api/external.go
- system/item/item.go
Another thank you to @ferhatelmas for the typo fixes!
In addition, I have added two new methods to the `item.Hookable` interface:
```go
BeforeAccept(http.ResponseWriter, *http.Request) error
AfterAccept(http.ResponseWriter, *http.Request) error
```
These add helpful functionality when needing to react to the one-time action of accepting content from an external source. I personally needed to do this and had previously hacked `BeforeSave` (which is called AFTER `BeforeAccept` and `Accept`), to look for and set a flag which indicated that content was newly saved to the CMS.  
This is being merged into master on the current release.
> [core] Documentation typo fixes, adding new Hookable methods: BeforeAccept & AfterAccept

- system/api/cors.go
- system/api/gzip.go
- system/api/handlers.go
- system/api/hide.go
- system/api/json.go
- system/api/omit.go
- system/api/push.go
- system/api/record.go
- system/item/item.go
This PR adds support to selectively omit arbitrary fields from a content API JSON response. Made accessible to Ponzu content types via the `item.Omittable` interface:
```go
type Omittable interface {
Omit() []string
}
```
The `[]string` returned by `Omit` is similar to the one returned by `item.Pushable#Push`, which contains the string names of the JSON tags for their corresponding struct fields. 
Additionally, there is some minor code reorganization to set a new pattern for adding new interfaces and their implementations to the API response code. Once an interface is added, like `item.Omittable`, its implementation should be done in a new file (or one whose domain/scope is similar) within the `system/api` package. The application of the interface should then be added in the handler at …
> [core] Adding support to omit fields from json response, minor code reorganization

- cmd/ponzu/main.go
- cmd/ponzu/options.go
- cmd/ponzu/paths.go
Created a file called 'paths.go', this way paths are separated from main logic, and also, will be able to use go's conditional building if we need it in any time (based on file names).
> Fix Windows build & run

- cmd/ponzu/main.go
- cmd/ponzu/paths.go
Again, thank you to @Sirikon for the help identifying and fixing these issues.
Now, the built output binary/executable of `$ ponzu build` is correctly located per OS filesystem differences when running `$ ponzu run`
> [core] fix path location for cross-platform compatibility

- README.md
- cmd/ponzu/add.go
- cmd/ponzu/main.go
- cmd/ponzu/options.go
- cmd/ponzu/usage.go
Reference issue #85. As discussed, this adds a `ponzu add` command to the CLI. It fetches the addon from its URI by wrapping `go get` then copies it to the projects local `./addons` directory. 
There is no switch for automatically installing. Based on the issue discussion that feature needs more thought, so has been omitted.
I've updated the README to include documentation on the command. 
It's been tested as per the approach in the README.
> ponzu add <addon URI>

- cmd/ponzu/add.go
- cmd/ponzu/paths.go
It's a 'path' getter and is used in many places of the CLI codebase, should be in paths.go, I think.
> Move getGOPATH method to paths.go

- system/api/server.go
- system/api/update.go
- system/db/content.go
- system/item/item.go
Allows for external api updates to content items by POST request such as:
/api/content/update?type=Review&id=1
Adds Updateable interface. Implementers are suggested to validate requests inside AcceptUpdate, likely using user.IsValid(req) to validate based on token/secret.
> Allow for external api updates to content items

- system/api/update.go
Allow flexibility for return of ErrNoAuth from either BeforeAcceptUpdate or AcceptUpdate.  Using BeforeAcceptUpdate will be more consistent with how auth validation for external is implemented.
> ErrNoAuth from either BeforeAcceptUpdate or AcceptUpdate will return 401

- cmd/ponzu/generate.go
- cmd/ponzu/templates/gen-checkbox.tmpl
- cmd/ponzu/templates/gen-content.tmpl
- cmd/ponzu/templates/gen-custom.tmpl
- cmd/ponzu/templates/gen-file.tmpl
- cmd/ponzu/templates/gen-hidden.tmpl
- cmd/ponzu/templates/gen-input.tmpl
- cmd/ponzu/templates/gen-richtext.tmpl
- cmd/ponzu/templates/gen-select.tmpl
- cmd/ponzu/templates/gen-tags.tmpl
- cmd/ponzu/templates/gen-textarea.tmpl
As referenced in the [community suggestion project](https://github.com/ponzu-cms/ponzu/projects/2#card-1540549), this PR adds the ability to define which type of HTML input to show in an editor view for a content type in the CMS. 
The specifier is entirely optional, and if not added the behavior is exactly the same as prior versions. To use, add a third parameter to the generated field, like so:
```bash
$ ponzu gen c song title:string artist:string:input description:string:richtext genre:string:select
```
In the `content/song.go` file generated, the fields' views will automatically be the following:
Title: Input
Artist: Input
Description: Richtext
Genre: Select
This saves time in the set-up phase for your content types and should also be helpful if you're looking for documentation on how …
> [cli] add input type specifier to generate content command

- management/manager/manager.go
- system/admin/handlers.go
- system/db/content.go
After using Ponzu in high-traffic a production environment for a few months, I noticed some of the content results were out of order :-1:  (both from the API and in the admin dashboard). With this PR, the sorted content buckets use a slightly different key identifier to avoid the natural order Bolt will store data in a bucket.
If you already have a lot of data in your CMS, just go through each content type and save one of the items -- this will trigger a re-sort and fix any out of order content.
Additionally,  the timestamps generated by Ponzu (rather than the dashboard editor) are now in UTC. This should make it easier to eventually deal with data moved from server to server.
> [core] better sort ordering and more reliable content API results

- README.md
- system/api/search.go
- system/api/server.go
- system/db/content.go
- system/db/init.go
- system/db/search.go
- system/item/item.go
- system/item/types.go
This PR adds the ability to enable indexing content on a per-type basis, to be searched through the new `/api/search?type=<Type>&q=<Query String>` endpoint, as partially detailed in #51.
A new interface in the `system/db` package, called `Searchable` contains two methods: `IndexContent() bool` and `SearchMapping() (*mapping.IndexMapping, error)`. `SearchMapping` has a default implementation on `item.Item` to set up the default index mapping from Bleve. In order to tell Ponzu to manage your content in Bleve's index, all you need to do is implement the `IndexContent` and return `true` from the method. 
The search endpoint can take any [query format supported by Bleve](http://www.blevesearch.com/docs/Query-String-Query/), as long as your underlying data types meet the requirements (dates for …
> [core] Configurable full-text search with Bleve + search API endpoint

- cmd/ponzu/generate.go
Fixes #111.
current list of reserved field names, as part of embedded `item.Item`: 
```go
var reservedFiledNames = map[string]string{
"uuid":      "UUID",
"item":      "Item",
"id":        "ID",
"slug":      "Slug",
"timestamp": "Timestamp",
"updated":   "Updated",
}
```
> [cli] fix regression bug in CLI field parser, catching reserved field names

- system/admin/handlers.go
- system/admin/upload/backup.go
- system/api/analytics/backup.go
- system/db/backup.go
This should get the ball rolling on issue #110. Please review 😄 
I did notice that the project doesn't have an overarching test strategy/implementation in place, hence the reason for the lack of test(s).
I wanted to get your opinion on how to add (or start) adding some test suites onto the project @nilslice. I was thinking of maybe using something like https://github.com/spf13/afero for mocking the `uploads/` directory. WDYT?
> Add context cancellation to backup routines

- cmd/ponzu/generate.go
- system/admin/handlers.go
- system/admin/upload/backup.go
- system/api/analytics/backup.go
- system/db/backup.go
Shout-out to @eticzon for closing out #110 - which handles failed or cancelled backup requests super nicely. Now, dropped requests or errors somewhere in the processing will stop processing the backup and save resources.  Thank you, @eticzon!
> [core] Add cancellation context to system backups

- system/addon/addon.go
- system/admin/handlers.go
- system/item/item.go
This PR adds new methods to the `item.Hookable` interface which enable Addons to intercept the point in time at which they are Enabled/Disabled as well adding more fine-grain control to the Admin actions on content, including Creating, Updating and Deleting. The method set for `item.Hookable` is a bit large, but as long as the content types embed `item.Item`, as expected, all these methods in the interface are implemented by default. No additional work is needed, but you now have more options to override and customize your system.
> [core] more Admin and new Addon lifecycle hooks

- cmd/ponzu/generate.go
- cmd/ponzu/templates/gen-content.tmpl
- cmd/ponzu/templates/gen-file-repeater.tmpl
- cmd/ponzu/templates/gen-input-repeater.tmpl
- cmd/ponzu/templates/gen-reference-repeater.tmpl
- cmd/ponzu/templates/gen-reference.tmpl
- cmd/ponzu/templates/gen-select-repeater.tmpl
This PR contains some updates to the CLI a bit to add the ability to generate references to other content types.. here's the syntax:
```bash
$ ponzu gen c author name:string bio:string:textarea city:string year_joined:int
$ ponzu gen c article title:string author:@author,name,city content:string:richtext photos:"[]string":file
```
The trailing `,name,city` suffix to `author:@author` set the displayed option names in the select dropdown inside the CMS. If you leave them blank, it defaults to `Author: {{ .id }}`
Additionally, any `[]T` slice type i.e. `photos:"[]string":file` in the example above, will automatically generate a `editor.FileRepeater`, or the "Repeater" for the view specifier (as long as one exists).
Currently, there are "Repeaters" for `file`, `select`, and `input` which will …
> [cli] adding reference type and auto-repeater generate syntax

- cmd/ponzu/usage.go
Tiny typo fix, spotted it because of the video (which is a good overview, thanks).
> fix typo retrun should be return

- management/format/csv.go
- system/admin/export.go
- system/admin/handlers.go
- system/admin/server.go
- system/admin/static/dashboard/css/admin.css
This PR adds the ability to trigger a download of the content per type in CSV format from within the admin dashboard. In order to add the CSV download button to the CMS, you need to implement the management/format package's `format.CSVFormattable` interface with its single method, `FormatCSV() []string`:
```go
func (b *Book) FormatCSV() []string {
return []string{
"id",
"timestamp",
"title",
"other_json_struct_tags",
}
}
```
Just like other Ponzu content extension interfaces, like `Push()`, you will return the JSON struct tags for the fields you want exported to the CSV file. These will also be the "header" row in the CSV file to give titles to the file columns. Keep in mind that all of `item.Item`'s fields are available here as well.
> [core] add CSVFormattable interface to export CSV formatted content

- system/admin/handlers.go
- system/api/create.go
- system/api/delete.go
We have all of the information, it's nice to be access the item's members in a natural way, without having to look at the request.
This was already done for the approveContentHandler, but here I added to the editHandler of admin, and the createHandler of the API.
> make a proper item for Hookable methods

- cmd/ponzu/main.go
- system/db/init.go
"Fix" for search not working when addons were enabled (https://github.com/ponzu-cms/ponzu/issues/153#issuecomment-305064094)
Index init was moved out of db.Init and put to main(), because addoon checker was initializing db together with search indexing initialisation in time when there were no item.Types defined so search index was always empty when using addons.
There is  no guarentee whatsoever that item.Types is defined even when called in main.
> Fix for search not working when addons are enabled

- system/db/init.go
Removing old ``InitSearchIndex``code from `db.Init`, so we do not have two Indexer Init calls.
Sorry, this got lost in last repeated PR.
> db.init cleanup

- .gitignore
- addons/github.com/bosssauce/reference/reference.go
Fixes HTML characters in reference options which were not being unescaped after the JSON decoding, making them display incorrectly in the admin UI.  
Also adds `.gitignore` file with commonly checked in Ponzu files/directories that shouldn't be in version control.
> [core] fix HTML escaping for select tag options in reference package

- system/admin/admin.go
There have been several issues filed where errors are reported during JSON decoding of references. 99% of them are solved by using the correct domain / hostname during development. This PR adds a suggested hostname during initialization (`/admin/init`) which looks at the client's `window.location.host||hostname` property and uses it, without the port number.
> [core] add default domain name to init form based on client hostname

- system/api/create.go
- system/db/init.go
`db.AddBucket(name string)` can be called from external packages to create new buckets during the system initialization. 
`db.Store() *bolt.DB` returns a handle to the underlying bolt.DB for `system.db`
> [core] add method to enable new buckets to be created by other packages and addons, cleanup

- cmd/ponzu/templates/gen-content.tmpl
By adding the String method to a content type generated by the CLI, it makes for easier and more obvious feature discovery so user's know to change the display of their items in the CMS UI. 
Credit to @jasonkeene for the suggestion at Boulder Gopher's meetup.
> [core] adding String method to generated content type with better default

- cmd/ponzu/upgrade.go
Allow `upgrade` command to pass `--dev` and `--fork` flags to reclone from development branches to make development & testing easier
> Upgrade from ponzu-dev or fork

- system/api/gzip.go
These changes move a defer block that closes the gzip writer into the gzip middleware handler.
Thanks @nilslice for the opportunity to contribute!
Closes #205
> Move defer statement into http handler function

- docs/src/Quickstart/Overview.md
It had been removed in #222, but it seems to be re-added accidentally.
> Remove unused extra backtick

- .circleci/test-setup.sh
- cmd/ponzu/add.go
- docs/src/Quickstart/Overview.md
- system/api/push.go
Fixes #245, due to old vendor of `golang.org/x/net/http2` w/r/t https://github.com/golang/net/commit/cbb82b59bc5199680c5bf34109e12097095dca9b
> merge contributions

- management/editor/elements.go
Added toolbar group `style` which includes `quote` and `code` along with `headings 1-6`. Also added `table`. Closes #207.
> Added heading styles and table to richtext toolbar.

- system/admin/upload/backup.go
- system/backup/archive.go
- system/search/backup.go
fixes #288 
* ArchiveFS will now follow the symlink if base dir is one.
The lack of proper error bubbling had caused me a bit of a headache, so:
* ArchiveFS errors will now be bubbled properly.
> Follow symlinks when archiving

- docs/src/Interfaces/Item.md
- system/api/handlers.go
- system/item/item.go
As discussed in issue #302, this provides two new hooks so that we can interact with the JSON response from the Ponzu API. Use cases mentioned so far include spellchecks, shortcode replacement and sanitization.
The function signatures are slightly different to the other hooks as the ```[]byte``` slice representing the JSON response is passed to both new hooks, and in the case of ```BeforeAPIResponse``` also returned ready to be sent by Ponzu.
```
BeforeAPIResponse(http.ResponseWriter, *http.Request, []byte) ([]byte, error)
AfterAPIResponse(http.ResponseWriter, *http.Request, []byte) error
```
After ```APIResponse``` is worth having in my mind, it may be useful for logging or notifications.
If this is OK, I will of course also amend the docs to reflect the new hooks, and make a separate …
> Adds BeforeAPIResponse and AfterAPIResponse hooks 

- management/editor/editor.go
- system/db/content.go
Started from my question on #308 about my needs to edit slug, I make some changes myself to achieve that.
First time contributing here. Honestly I'm not that familiar about the design of this repo. I've tried to make changes as unobtrusive as possible, but let me know if the changes is not acceptable.
Actually there are several concerns when I'm working on this:
1. I'm not sure whether slug is should to be editable or not
2. Currently on the editor slug data is sent twice, from a hidden field and a disabled text field. Not sure if it's intended or not, but I'm using both value to check if slug is being edited by user
3. `value.Get("field_name")` only return the first value of the specified field, I use `value["field_name"][1]` to get the second value of a field. Not sure if it's deemed …
> make slug editable

- addons/github.com/bosssauce/reference/reference.go
- management/editor/elements.go
- management/editor/repeaters.go
This PR is based on feature request on #280 **Sorting results in SelectRepeater**
changes:
- Select options now always ordered alphabetically
> Sorting results in Select and SelectRepeater

- cmd/ponzu/generate.go
- cmd/ponzu/templates/gen-content.tmpl
- docs/src/CLI/General-Usage.md
changes:
- We can define main field when generating content from CLI by adding `*` before the field name.
- Update method to parse field, name, and json tag. Now handle `*` prefix for defining main field.
- Update content template to dynamically change the field used on `String()` methos
> Add main field specifier on CLI

- system/admin/server.go
- system/admin/upload/upload.go
- system/api/analytics/init.go
- system/cfg/env.go
- system/db/init.go
- system/search/backup.go
- system/search/search.go
- system/tls/devcerts.go
- system/tls/enable.go
- system/tls/enabledev.go
Running ponzu-cms inside a docker container, and maintaining
data files in a volume (or several) was not possible with the
previous directory schema without copying files or binaries
to the volume.
This commit adds several environment variables to allow the
administrator to specify paths for directories while
retaining backwards compatibility.
- PONZU_DATA_DIR : is the directory where all the data and other
directories will be stored, still the other
directories can be controlled by the other env
variables.
- PONZU_TLS_DIR : is the directory to store devcerts and autocerts
- PONZU_ADMINSTATIC_DIR : directory where the admin static files are
served from.
- PONZU_UPLOAD_DIR: upload files directory
- PONZU_SEARCH_DIR: index directory for searches
> Allow data directories outside pwd
